AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  GeoImportsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Timeout: 10
      Tracing: Active
      Events:
        GeoImportsEveryMondayPre1HourEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 5 ? * MON *)
        GeoImportsEveryMondayEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 ? * MON *)
